### PR TITLE
Add image tag for post thumbnail

### PR DESCRIPTION
**Pull request by porjo**

### CODE REVIEW

**Comment by alexandersokolow** [comment]
Hi, thanks for the PR!

Any idea what RSS reader I could use on Arch to test this? I usually use newsboat, which is in the terminal. Tried Akregator but it didn't display any images.

Edit: Merging the PR, since it doesn't seem to break anything & I want to test it with some online reader.

**Comment by porjo** [comment]
my mistake - it looks like the `<image>` tag is only meant for the channel, not for items!  https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt

Looking at other feeds, i can see `<itunes:image>` tag being used for this - I guess it's an Apple extension.

**Comment by alexandersokolow** [comment]
I looked & there's also <media:thumbnail>, you'll find that on youtube RSS feeds & it is fairly well supported across rss readers.
Didn't have the time to properly try it out myself, but if you can get that to work feel free to open another PR.

**Comment by porjo** [comment]
I've [made more changes in my branch](https://github.com/alexandersokolow/rss-gen/compare/master...porjo:rss-gen:image) to use `<itunes:image>` and `<media:thumbnail>` tags. I tested with [quiterss](https://github.com/QuiteRSS/quiterss) on Linux and it shows thumbs for `<media:thumbnail>`, but not for `<itunes:image>`. Let me know if you'd like me to send another PR.

**Comment by alexandersokolow** [comment]
Thanks, have added your code to the main branch (& the rssgen.xyz instance). It's not working on newsblur.com, but I guess it's a step forward haha

**Pull request merged**
